services:
  app:
    image: richarvey/nginx-php-fpm:latest
    container_name: www
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Not24get
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Not24get
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: app_user
      PMA_PASSWORD: Not24get
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

